### ISSUE TITLE
When I compile the project, an error "src/caffe/3rdparty/reduce.cu(44): error: identifier "__shfl_down" is undefined"

### ISSUE THREAD

**Issue by xuyang1102** [yalecyu/crnn.caffe#8]
When I compile the project, an error "src/caffe/3rdparty/reduce.cu(44): error: identifier "__shfl_down" is undefined",  how to solve it ?

**Comment by yalecyu** [comment]
Your caffe environment may be problematic. You can search the information from internet. I am not familiar with the environment of caffe.

**Comment by xuyang1102** [comment]
Can I train the Chinese characters recognition use this code ?

**Comment by yalecyu** [comment]
Of course. @xuyang1102

**Comment by xuyang1102** [comment]
@yalecyu  OK  thx

**Comment by xuyang1102** [comment]
你好，我再问下，做中文文本识别的话，训练样本图像是分割出来的文本行？ 标注的gt用什么形式呢？ 我看自带的例子只是针对验证码的吧

**Comment by yalecyu** [comment]
我对你的需求还并不是很清晰。你可以给我发邮件详细描述一下你的需求。
